---
title: "Data Processing"
author: "Laura Brockington"
date: "2023-03-23"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r setup, message=F}
#loading in necessary packages
library(here); library(tidyverse); library(lubridate); library(zoo)
library(trend); library(sf); library(leaflet); 
library(mapview); mapviewOptions(fgb = FALSE); library(dataRetrieval); library(ggspatial); library(rgdal); library(RColorBrewer); library(sp)

#checking my working directory
here()

#setting my theme

#setting mapview options
mapviewOptions(basemaps = c("Esri.WorldShadedRelief", "OpenStreetMap.DE"))
```

```{r}
#reading in my data file
bat_data_raw <- read.csv(here("Data/Raw/Bat_Activity_Insect_Abundance_Data.csv"), 
                     stringsAsFactors = TRUE)

#setting date column as date class
bat_data_raw$Date <- mdy(bat_data_raw$Date)
```

**Research questions**
1. Have temperatures changed from 2017 to 2020 along the Colorado River in Grand Canyon, AZ?
2. Has bat activity changed from 2017 to 2020 along the Colorado River in Grand Canyon, AZ?
3. What factors most influence changes in bat activity (temperature, prey availability, moon phase, location)?

```{r}
#wrangling data to include only variables of interest for linear model
bat_data_lm <-
  bat_data_raw %>%
  select(Date, LunarPhase, DailyTemp, Site, TotalCalls, TotalPreyRate)

#exporting processed data file to processed folder in R project file
write.csv(bat_data_lm, row.names = FALSE, 
          file = "./Data/Processed/Bat_Activity_Insect_Abundance_Data_linearmodel.csv")

#wrangling data to include only variables of interest for spatial analyses
bat_data_spatial <-
  bat_data_raw %>%
  st_as_sf(coords = c('Longitude','Latitude'),
           crs=4326) %>%
  select(Date, LunarPhase, DailyTemp, Site, TotalCalls, TotalPreyRate, geometry)

#retrieving water data from USGS
siteNumber <- "09402500"
COriverInfo <- readNWISsite(siteNumber)
rawDailyData_COriver_discharge <- readNWISdv(
  siteNumber, "00060", statCd = "00003",
  "2017-04-29", "2020-10-22"
)

#converting COriverInfo into spatial dataset
COriver_discharge_site <-
  COriverInfo %>%
  st_as_sf(coords = c('dec_long_va','dec_lat_va'),
           crs=4269)

#reading in CO river
CO_river_utm <- st_read('./Data/Raw/az_hydro_routesNAD83/az_hydro_routesNAD83.shp') %>% filter(NAME == "Colorado River")
CO_river_utm <- st_zm(CO_river_utm)

#transforming data to all be NAD83 UTM zone 12N (26912)
bat_data_sf_utm <- st_transform(bat_data_spatial, 26912)
CO_river_discharge_utm <- st_transform(COriver_discharge_site, 26912)

#plotting COriverInfo
overview_map <- mapView(CO_river_utm, 
        color = "royalblue3",
        map.types = "OpenStreetMap.DE",
        layer.name = "Colorado River") + 
  mapView(bat_data_sf_utm, 
          zcol = "TotalCalls", 
          cex = 3, 
          lwd = 0.3,
          alpha = 0.7,
          col.regions = brewer.pal(10, "Reds"),
          map.types = "OpenStreetMap.DE",
          layer.name = "Bat Survey Sites (Total Calls)") + 
  mapView(CO_river_discharge_utm,
          col.regions = "gold",
          map.types = "OpenStreetMap.DE",
          layer.name = "Discharge Site")
  
overview_map@map %>% setView(-112.0777, 36.2, zoom = 8)

"https://waterdata.usgs.gov/blog/dataretrieval/"
```

```{r}
#exploring data
dim(bat_data_lm)
summary(bat_data_lm)
ggplot(bat_data_lm, aes(x=DailyTemp, y=TotalCalls)) +
  geom_point()

dim(bat_data_spatial)
summary(bat_data_spatial)
ggplot() +
  geom_sf(data = bat_data_spatial)
```


```{r}
#source: https://www.usgs.gov/data/bat-activity-and-insect-abundance-data-along-colorado-river-grand-canyon-az
```

