---
title: "Data Analysis"
author: "Laura Brockington"
date: "2023-03-27"
output: pdf_document
editor_options: 
  chunk_output_type: console
---

```{r time series}
#time series analysis
discharge_plot <- #plotting discharge over time
ggplot(daily_discharge_processed, aes(x = Date, y = discharge)) +
  geom_line() +
  ylab("Discharge (units)") +
  xlab("Year") +
  ggtitle("Colorado River Discharge during Bat Monitoring") +
  scale_x_date(breaks = "years", date_labels = "%Y") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
print(discharge_plot)

#there was a controlled flood of the Colorado River in the Grand Canyon Nov, 2018 (huge peak in graph).

summary(daily_discharge_processed$discharge) #no NAs

f_month <- month(first(daily_discharge_processed$Date))
f_year <- year(first(daily_discharge_processed$Date))
f_day <- day(first(daily_discharge_processed$Date))

daily_discharge_ts <- ts(daily_discharge_processed$discharge, 
                             start = c(f_year, f_month, f_day), 
                             frequency = 365) #creating daily time series object

daily_discharge_decomposed <- stl(daily_discharge_ts, s.window = "periodic")
#decomposing the daily time series

plot(daily_discharge_decomposed) #plotting the components

daily_discharge_trend <- trend::smk.test(daily_discharge_ts)
daily_discharge_trend
summary(daily_discharge_trend)

#there is a statistically significant trend (with seasonality)

#Extracting all components and adding together the trend and remainder
daily_discharge_components <- 
  as.data.frame(daily_discharge_decomposed$time.series[,2:3])

daily_discharge_nonseasonal <- 
  mutate(daily_discharge_components,
         Non_seasonal = trend + remainder,
         Date = daily_discharge_processed$Date)

#16
daily_discharge_nonseasonal_ts <- 
  ts(daily_discharge_nonseasonal$Non_seasonal, 
                               start = c(f_year, f_month, f_day), 
                               frequency = 365) #creating time series object

#running non-seasonal Mann-Kendall on monthly average after removing seasonality
daily_discharge_nonseasonal_trend <-
  trend::mk.test(daily_discharge_nonseasonal_ts)
daily_discharge_nonseasonal_trend

ns_discharge_plot <- #plotting discharge over time
ggplot(daily_discharge_nonseasonal, aes(x = Date, y = Non_seasonal)) +
  geom_point(size=1, alpha=0.7, color="steelblue4") +
  geom_line(lwd=0.1, color = "steelblue2") +
  ylab("Discharge (units)") +
  xlab("Year") +
  geom_smooth(method = "lm", color = "palevioletred4", se = F) +
  scale_x_date(breaks = "years", date_labels = "%Y")
print(ns_discharge_plot)
```

```{r spatial}
#spatial analysis

#plotting COriverInfo
overview_map <- mapView(CO_river_utm, 
        color = "royalblue3",
        map.types = "OpenStreetMap.DE",
        layer.name = "Colorado River") +
  mapView(bat_data_sf_utm, 
          zcol = "TotalCalls", 
          cex = 5, 
          lwd = 0.3,
          alpha = 0.8,
          col.regions = brewer.pal(10, "Purples"),
          map.types = "OpenStreetMap.DE",
          layer.name = "Bat Survey Sites (Total Calls)") +
  mapView(CO_river_discharge_utm,
          col.regions = "gold",
          map.types = "OpenStreetMap.DE",
          layer.name = "Discharge Site")
  
overview_map@map %>% setView(-112.0777, 36.2, zoom = 8)

```

```{r linear model}
#linear model

#checking assumptions
par(mfrow = c(2,2), mar=c(4,4,4,4))
plot(irradiance.regression)
par(mfrow = c(1,1))
  
#plots
ggplot(daily_bat_discharge, aes(x = Date, y = TotalCalls)) +
  geom_point() +
  ylab("# of Bat Calls") +
  xlab("Date") +
  geom_smooth(method = lm, col = "royalblue", se = F) +
  ggtitle("Daily Number of Bat Calls Across Survey Timeline") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
print(bat_plot)

bat_temp_plot <-
ggplot(bat_data_monthly, aes(x = mean_temp, y = mean_calls)) +
  geom_point() +
  ylab("Mean # Bat Calls") +
  xlab("Mean Temperature (C)") +
  geom_smooth(method = lm, col = "royalblue", se = F) +
  ggtitle("Mean Monthly Bat Calls") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
print(bat_temp_plot)

bat_lunar_plot <-
ggplot(bat_data_processed, aes(x = LunarPhase, y = TotalCalls)) +
  geom_boxplot() +
  ylab("# Bat Calls") +
  xlab("Lunar Phase")
print(bat_lunar_plot)

qqnorm(daily_bat_discharge$TotalCalls); qqline(daily_bat_discharge$TotalCalls)

lm_bat_prey <- lm(data= daily_bat_discharge, TotalCalls ~ TotalPreyRate)
summary(lm_bat_prey)

lm_bat_veg <- lm(data= daily_bat_discharge, TotalCalls ~ TallVegByMSU)
summary(lm_bat_veg)

aov_bat_site <- aov(data = daily_bat_discharge, TotalCalls ~ Site)
summary(aov_bat_site)

bartlett.test(daily_bat_discharge$TotalCalls ~ daily_bat_discharge$LunarPhase)
aov_bat_lunar <- aov(data = daily_bat_discharge, TotalCalls ~ LunarPhase)
summary(aov_bat_lunar)

#running AIC to determine which set of variables if best to predict # bat calls
aic_all <- lm(data = daily_bat_discharge, TotalCalls ~ DailyTemp + TallVeg + LunarPhase + TotalPreyRate + discharge)
step(aic_all)

#running multiple regression on variables from AIC
lm <- lm(data = daily_bat_discharge, TotalCalls ~ DailyTemp + TallVeg + discharge)
summary(lm)

par(mfrow = c(2,2), mar=c(4,4,4,4))
plot(lm)
par(mfrow = c(1,1))

#ancova <- aov(data = daily_bat_discharge, TotalCalls ~ DailyTemp + LunarPhase + TotalPreyRate + discharge)
#Anova(ancova, type = "III")

#scale_x_date(breaks = "1 month", labels = date_format("%B"))
```

